module.exports = [
  'Education',
  'Movies & Entertainment',
  'Food & Dining',
  'Groceries',
  'Health & Beauty',
  'Sports & Fitness',
  'Home & Living',
  'Electronics',
  'Fashion',
  'Shopping',
  'Transportation',
  'Travel & Hotels',
  'Gaming',
  'Recharge & Utilities',
  'Banking & Insurance',
  'Vehicles',
  'Services',
  'Other',
];
